# Maintainer: Opencreek Technogoly UG
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=creekey-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="Story your Private Keys on your Phone!"
url="https://creekey.io"
license=("UNLICENSED")
arch=("x86_64")
provides=("creekey")
conflicts=("creekey")
source=("https://github.com/opencreek/creekey/releases/download/v$pkgver/creekey-$pkgver-x86_64.tar.gz")
sha256sums=("aa4190f0a199333c495151d393175cceded3e3e4408a1060b459784c9c7a5863")

package() {
    install -Dm755 creekey -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
