# Maintainer: Opencreek Technogoly UG
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=creekey-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="Story your Private Keys on your Phone!"
url="https://creekey.io"
license=("UNLICENSED")
arch=("x86_64")
provides=("creekey")
conflicts=("creekey")
source=("https://github.com/opencreek/creekey/releases/download/v$pkgver/creekey-$pkgver-x86_64.tar.gz")
sha256sums=("bc8caf3e3c74fcaf8e1e65a083e6b1f58533ea7dbb0c9046a0d5e85ec87ec384")

package() {
    install -Dm755 creekey -t "$pkgdir/usr/bin"
    install -Dm644 "${srcdir}"/unix/creekey.service "$pkgdir"~/.config/systemd/user/creekey.service
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
